#!/usr/bin/env python
# A simple native messaging host that receives url and plays in natvie app

import struct
import sys
import subprocess
from subprocess import check_output

# Thread that reads messages from the webapp.
def read_thread_func(queue):
  message_number = 0
  while 1:
    # Read the message length (first 4 bytes).
    text_length_bytes = sys.stdin.read(4)

    if len(text_length_bytes) == 0:
      sys.exit(0)

    # Unpack message length as 4 byte integer.
    text_length = struct.unpack('i', text_length_bytes)[0]

    # Read the text (JSON object) of the message.
    text = sys.stdin.read(text_length).decode('utf-8')

    # For debugging on osx
    # text = check_output(['/usr/local/bin/youtube-dl', '-f', '18', '-g', 'http://www.youtube.com' + text[1:-1]])
    # subprocess.call('/Applications/VLC.app/Contents/MacOS/VLC "'+ text.rstrip() + '"', shell=True)

    # Get URL using youtube-dl
    text = check_output(['youtube-dl', '-g', 'http://www.youtube.com' + text[1:-1]])

    # Play using omxplayer
    subprocess.call('lxterminal -e omxplayer -o hdmi "'+ text.rstrip() + '"', shell=True)

def Main():
    read_thread_func(None)
    sys.exit(0)

if __name__ == '__main__':
  Main()
